services:
  # Primary database for the local WordPress development environment.
  # Image from: https://hub.docker.com/_/mysql
  db:
    image: &db_img mysql:8.4
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./_db:/docker-entrypoint-initdb.d
      # - ./_log/mysql:/var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # command: >
    #   --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Ideas On Purpose's local WordPress development environment.
  # Update image version with `docker run ideasonpurpose/wordpress init`
  # Project info: https://github.com/ideasonpurpose/docker-wordpress-dev
  wordpress:
    depends_on:
      - db
    # image: &wp_img ideasonpurpose/wordpress:dev
    image: &wp_img ideasonpurpose/wordpress:6.7.2
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/themes/${npm_package_name:-ioptheme}:/var/www/html/wp-content/themes/${npm_package_name:-ioptheme}
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ${IOP_DEV_PLUGIN_1:-/tmp/null:/tmp/IOP_DEV_PLUGIN_1}
      - ${IOP_DEV_PLUGIN_2:-/tmp/null:/tmp/IOP_DEV_PLUGIN_2}
      - ${IOP_DEV_PLUGIN_3:-/tmp/null:/tmp/IOP_DEV_PLUGIN_3}
      - ${IOP_DEV_PLUGIN_4:-/tmp/null:/tmp/IOP_DEV_PLUGIN_4}
      - ${IOP_DEV_PLUGIN_5:-/tmp/null:/tmp/IOP_DEV_PLUGIN_5}
      - ${IOP_DEV_PLUGIN_6:-/tmp/null:/tmp/IOP_DEV_PLUGIN_6}
      - ${IOP_DEV_PLUGIN_7:-/tmp/null:/tmp/IOP_DEV_PLUGIN_7}
      - ${IOP_DEV_PLUGIN_8:-/tmp/null:/tmp/IOP_DEV_PLUGIN_8}
      - ./webpack/xdebug:/tmp/xdebug

    # Publish port 80 to an ephemeral host port to prepare for future local build tools
    ports:
      - "80"

    # Internally expose port 9003 for XDebug and profiling
    expose:
      - 9003

    # Link external plugin projects by defining host:container path pairs in .env
    environment:
      IOP_DEV_PLUGIN_1:
      IOP_DEV_PLUGIN_2:
      IOP_DEV_PLUGIN_3:
      IOP_DEV_PLUGIN_4:
      IOP_DEV_PLUGIN_5:
      IOP_DEV_PLUGIN_6:
      IOP_DEV_PLUGIN_7:
      IOP_DEV_PLUGIN_8:

    # Apache will throw errors for any ulimit value below 8192
    # NOTE THAT THIS MIGHT BE MORE THAN THE SYSTEM OFFERS
    # TODO: Still true?
    # TODO: Testing removal. 2025-03-18
    # ulimits:
    #   nofile: 8192

    # Required for iptables port-mapping to work inside the Docker image
    # This is used to fix a PHP/WordPress issue where internal requests
    # from Site Health tried to load from external ports.
    cap_add:
      - NET_ADMIN

  # # TODO: Deprecated and likely ready to remove 2025-03-18
  # # Ideas On Purpose's development toolchain
  # # Image from: https://hub.docker.com/r/ideasonpurpose/docker-build
  # tools:
  #   # image: ideasonpurpose/docker-build:dev
  #   image: ideasonpurpose/docker-build:0.17.2
  #   user: "${UID:-1000}:${GID:-1000}"
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - .:/usr/src/site/
  #   ports:
  #     - "${npm_config_port:-8080}:8080"
  #   environment:
  #     PORT: ${npm_config_port:-8080}
  #   entrypoint: npm run
  #   command: start

  # Utility service for running composer commands
  # Image from: https://hub.docker.com/_/composer
  composer:
    image: composer:2.8
    profiles: ["utility"]
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  # Utility service which exposes wp-cli. Useful for testing pre-releases
  # Update image version with `docker run ideasonpurpose/wordpress init`
  # Project info: https://github.com/ideasonpurpose/docker-wordpress-dev
  wp-cli:
    depends_on:
      - db
      - wordpress
    image: *wp_img
    profiles: ["utility"]
    user: www-data
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/themes/${npm_package_name:-ioptheme}:/var/www/html/wp-content/themes/${npm_package_name:-ioptheme}
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    environment:
      - WP_CLI_CACHE_DIR=/tmp/wp-cli
      - WP_CLI_DISABLE_AUTO_CHECK_UPDATE=true
    command: wp theme activate ${npm_package_name:-ioptheme}

  # Runs phpMyAdmin on port 8002
  # Image from: https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    profiles: ["utility"]
    ports:
      - "${npm_config_port:-8002}:80"
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: ~
      UPLOAD_LIMIT: 1G
    command: |
      bash -c  'echo &&
                echo -e  "🛠   \033[33mStarting phpMyAdmin at\033[0m \033[36mhttp://localhost:${npm_config_port:-8002}\033[0m" &&
                echo &&
                /docker-entrypoint.sh apache2-foreground'

  # XDebug profile viewer at http://localhost:9001 (change port with --port=xxxx)
  # Enable profiling by appending `?XDEBUG_PROFILE=1` to any request
  # https://hub.docker.com/r/wodby/webgrind
  webgrind:
    image: wodby/webgrind:1.9
    profiles: ["utility"]
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${npm_config_port:-9004}:8080"
    depends_on:
      - wordpress
    volumes:
      - ./webpack/xdebug:/tmp
    environment:
      WEBGRIND_DEFAULT_TIMEZONE: America/New_York
    command: |
      bash -c  'echo &&
                echo -e  "🔍  \033[33mStarting WebGrind server at\033[0m \033[36mhttp://localhost:${npm_config_port:-9004}\033[0m" &&
                echo -e  "⏱️   Profile any request by adding \033[1;35m?XDEBUG_PROFILE=1\033[0m to the url" && 
                echo &&
                php -S 0.0.0.0:8080 index.php
                '

  # Dumps the current database to _db/theme-YYYY-MM-DDTHHMMSS.sql.gz
  db-dump:
    image: *db_img
    profiles: ["utility"]
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src
    environment:
      MYSQL_DATABASE: wordpress
      OWNER_GROUP: "${UID:-1000}:${GID:-1000}"

    # NOTE: The datbase dumpfile will include these CREATE/USE commands:
    #           CREATE DATABASE `wordpress`;
    #           USE `wordpress`;
    #       to drop those lines, remove  "--databases" from the mysqldump command
    command: |
      bash -c  'for i in {1..10}
                do echo -e "⏳  \033[33mWaiting for DB server...\033[0m" &&
                  mysql --ssl-mode=DISABLED -s -h db -e "exit" && break || sleep 3
                done &&
                sleep 2 &&
                echo -e "✔️   \033[32mConnected to DB\033[0m" &&
                export DUMPFILE="/usr/src/'${npm_package_name:-dumpfile}'-$$(date +%FT%H%M%S).sql" &&
                echo $${DUMPFILE} &&
                mysqldump --ssl-mode=DISABLED -hdb --databases $${MYSQL_DATABASE} > "$${DUMPFILE}" &&
                gzip "$${DUMPFILE}" &&
                chown -R $${OWNER_GROUP} /usr/src &&
                echo "Successfully dumped database to \"$${DUMPFILE}.gz\""'

  # Reloads the database from the first found *.sql dumpfile in _db
  db-reload:
    image: *db_img
    profiles: ["utility"]
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src/dumpfiles
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c  'for i in {1..10}
                do echo -e "⏳  \033[33mWaiting for DB server...\033[0m" &&
                  mysql --ssl-mode=DISABLED -s -h db -e "exit" && break || sleep 3
                done &&
                sleep 2 &&
                echo -e "✔️   \033[32mConnected to DB\033[0m" &&
                mysqladmin --ssl-mode=DISABLED -hdb -v -f drop $${MYSQL_DATABASE} &&
                mysqladmin --ssl-mode=DISABLED -hdb -v -f create $${MYSQL_DATABASE} &&
                echo Database \"$${MYSQL_DATABASE}\" created &&
                echo Reloading database from dumpfile &&
                mysql --ssl-mode=DISABLED -hdb $${MYSQL_DATABASE} < $$(ls /usr/src/dumpfiles/*.sql | tail -n1)'

  # Activates the theme directly in the database
  theme-activate:
    image: *db_img
    profiles: ["utility"]
    depends_on:
      - db
    volumes:
      - ./_db:/usr/src/dumpfiles
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c  'for i in {1..10}
                do echo -e "⏳  \033[33mWaiting for DB server...\033[0m" &&
                  mysql --ssl-mode=DISABLED -s -h db -e "exit" && break || sleep 3
                done &&
                sleep 2 &&
                echo -e "✔️   \033[32mConnected to DB\033[0m" &&
                if [[ $$(mysql --ssl-mode=DISABLED -s -h db $${MYSQL_DATABASE} -e "SHOW TABLES LIKE \"wp_options\"") ]]
                then
                  echo -e "🎨  \033[36mActivating theme \033[0m\033[1m${npm_package_name:-ioptheme}\033[0m"
                  mysql --ssl-mode=DISABLED -h db $${MYSQL_DATABASE} \
                        -e "UPDATE wp_options \
                            SET option_value = \"'${npm_package_name:-ioptheme}'\" \
                            WHERE option_name in (\"template\",\"stylesheet\")"
                else
                  echo -e "Unable to activate theme: \033[31m'\'wp_options\'' table does not exist.\033[0m"
                  echo "To recreate an existing site, copy the site'\''s DB dumpfile into _db"
                  echo If this project is starting from an empty database, you can ignore this message.
                fi'

  # Repairs permissions for known project files and directories
  repair-permissions:
    image: *wp_img
    profiles: ["utility"]
    volumes:
      - .:/usr/src/site
    environment:
      OWNER_GROUP: "${UID:-1000}:${GID:-1000}"
    entrypoint: /usr/local/bin/permissions.sh

  # Locally mirror remote sites by pulling the database, plugins and uploads
  # Remote connections are configured in the project's .env file
  pull:
    image: *wp_img
    profiles: ["utility"]
    volumes:
      - .:/usr/src/site
    entrypoint: |
      /usr/local/bin/pull.sh
    environment:
      OWNER_GROUP: "${UID:-1000}:${GID:-1000}"
      SSH_KEY_PATH:
      SSH_LOGIN:
      SSH_USER:
      SSH_PORT:
      SSH_WP_CONTENT_DIR:
    secrets:
      - SSH_KEY

  # Run the init script from ideasonpurpose/wordpress:latest (intentionally "latest")
  # to refresh tooling and bring the project inline with our boilerplate
  # Project info: https://github.com/ideasonpurpose/docker-wordpress-dev
  refresh:
    # image: ideasonpurpose/wordpress:dev
    image: ideasonpurpose/wordpress:latest
    profiles: ["utility"]
    volumes:
      - .:/usr/src/site
    command: init

secrets:
  SSH_KEY:
    file: ${SSH_KEY_PATH:-~/.ssh/your_ssh_private_key}

volumes:
  db_data:
    name: ${npm_package_name:-ioptheme}_db
  wp_data:
    name: ${npm_package_name:-ioptheme}_wp
